openapi: 3.0.1

info:
  title: Portfolio Server Interface
  version: '1.0'
  description: "Interface for communicating with the Portfolio Server"
  contact:
    name: Joe Csurgai
    email: mcsurgai@gmail.com

paths:
  /users:
    get:
      tags:
        - web-user-interface
      summary: "Finds all web users"
      operationId: loadAllWebUsers
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "models/rest-models.yaml#/components/schemas/WebUserDto"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
