export enum Constants {
  EMPTY = "",
  SPACE = " ",
  DASH = "-",
  SPACE_DASH_SPACE = " - ",
  SLASH = "/",
  BACKSLASH = "\\",
  PLUS = "+",
  MINUS = "-",
  COLON = ":",
  SEMICOLON = ",",
  COMMA = ",",
  UNDERLINE = "_",
  SINGLE_QUOTE = "'",
  DOUBLE_QUOTE = '"',
  HASHTAG = "#",
  DOT = ".",
  PERCENT = "%",
}
