export enum Certificate {
  MECHANICAL_ENGINEER_BSC_DEGREE,
  CAD_CAM_CNC_PROGRAMMER_TECHNOLOGIST_CERTIFICATE,
  JUNIOR_JAVA_BACKEND_DEVELOPER_CERTIFICATE,
  JUNIOR_ENTERPRISE_JAVA_BACKEND_DEVELOPER_CERTIFICATE,
  FRONTEND_DEVELOPMENT_PROFESSIONAL_CERTIFICATE,
  AZURE_900_CERTIFICATE,
  AZURE_204_CERTIFICATE,
  GITLAB_CI_CD_ASSOCIATE_CERTIFICATE
}

export interface CertificateDetail {
  id: string,
  date: string,
  link?: string
}