logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081

spring:
  application:
    name: Portfolio server

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Monkey92
    #    tomcat:
    #      driver-class-name: org.postgresql.Driver
    
  flyway:
    enabled: false
    
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
      
springdoc:
  api-docs:
    path: api-docs
  cache:
    disabled: true
  swagger-ui:
    path: swagger
    
#  datasource:
#    tomcat:
#      driver-class-name: org.postgresql.Driver
#      initial-size: 8
#      log-abandoned: true
#      max-active: 32
#      max-idle: 16
#      max-wait: 10000
#      min-evictable-idle-time-millis: 55000
#      min-idle: 4
#      remove-abandoned: true
#      remove-abandoned-timeout: 600
#      suspect-timeout: 300
#      test-on-borrow: true
#      time-between-eviction-runs-millis: 34000
#      validation-interval: 34000
#      validation-query: select 1 from dual
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    url: ${spring.datasource.tomcat.url}
#  mvc:
#    throw-exception-if-no-handler-found: true
#    pathmatch:
#      matching-strategy: ant-path-matcher
#  jpa:
#    database-platform: org.hibernate.dialect.Oracle12cDialect
#    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false
#        use_sql_comments: false
#        generate_statistics: false
#        order_inserts: true
#        order_updates: true
#        hbm2ddl:
#          auto: validate
#        jdbc:
#          batch_versioned_data: true
#          fetch_size: 1000
#          batch_size: 1000
#        auto_quote_keyword: true
#        default_batch_fetch_size: 1000
#        batch_fetch_style: dynamic
#    hibernate:
#      ddl-auto: validate
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false
#
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#user-request-header-key: x-auth-user
