export enum Constants {
  EMPTY = "",
  SPACE = " ",
  DASH = "-",
  SPACE_DASH_SPACE = " - ",
  SLASH = "/",
  SPACE_SLASH_SPACE = " / ",
  BACKSLASH = "\\",
  PLUS = "+",
  MINUS = "-",
  COLON = ":",
  COLON_SPACE = ": ",
  SEMICOLON = ",",
  COMMA = ",",
  COMMA_SPACE = ", ",
  UNDERLINE = "_",
  SINGLE_QUOTE = "'",
  DOUBLE_QUOTE = '"',
  HASHTAG = "#",
  DOT = ".",
  PERCENT = "%",
  SPACE_PARENTHESIS_LEFT = " (",
  PARENTHESIS_LEFT = "(",
  PARENTHESIS_RIGHT = ")",
}
